### PATH ###
CKPT_PATH: "/opt/pytorch/DFformer/checkpoints"
DB_PATH: "/opt/pytorch/DFformer/databases"
WEIGHT_PATH: null
WEIGHT_FILENAME: null

### SETTING ###
SEED: 42
GPU_NUM: "0"
num_workers: 6

### DATASET ###
db_name: "SleepEDF"
num_classes: 5
num_subjects: 20
inter_information_length: 30 # epoch_length
origin_ival: [0, 3000]
seq_len: 3000

### MANUAL ###
EPOCHS: 30
target_subject: 0
target_session: null
train_data_ratio: 100
use_token: False
apply_cls_head: True
model_name: "dfformer"
